nyc_taxi_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      port: "{{ env_var('DB_PORT', '5433') | int }}"
      user: "{{ env_var('DB_USER', 'postgres') }}"
      password: "{{ env_var('DB_PASSWORD', '1234') }}"
      dbname: "{{ env_var('DB_NAME', 'nyc_taxi') }}"
      schema: gold
      threads: 4
