services:
  airflow-webserver:
    build: .
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:1234@host.docker.internal:5433/airflow
      AIRFLOW__CORE__FERNET_KEY: '4YAJSGW9Nib78qJJaDjWTlxodK5sa_ddDtrwhGwB0d4='
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      DB_HOST: host.docker.internal
      DB_PORT: 5433
      DB_NAME: nyc_taxi
      DB_USER: postgres
      DB_PASSWORD: "1234"
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - .:/opt/airflow
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: webserver

  airflow-scheduler:
    build: .
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:1234@host.docker.internal:5433/airflow
      AIRFLOW__CORE__FERNET_KEY: '4YAJSGW9Nib78qJJaDjWTlxodK5sa_ddDtrwhGwB0d4='
      DB_HOST: host.docker.internal
      DB_PORT: 5433
      DB_NAME: nyc_taxi
      DB_USER: postgres
      DB_PASSWORD: "1234"
    volumes:
      - .:/opt/airflow
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: scheduler

  metabase:
    image: metabase/metabase
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - ./metabase-data:/metabase-data

